### ISSUE TITLE
overridePermissions in puppeteer-extra with StealthPlugin() is not working...

### ISSUE THREAD

**Issue by footpatrolqueue** [berstend/puppeteer-extra#214] opened 2020-06-01 14:08 UTC
When I use overridePermissions my code is working in normal puppeteer or in puppeteer-extra without StealthPlugin() without any problem, but as soon as you add the StealthPlugin() its just not overriding anymore..

`const context = browser.defaultBrowserContext();
`

`context.overridePermissions("https://www.zalando.de/", ["geolocation", "notifications", "push", "midi", "camera", "microphone", "speaker", "device-info", "background-sync", "bluetooth", "persistent-storage", "ambient-light-sensor", "accelerometer", "gyroscope", "magnetometer", "clipboard", "accessibility-events", "clipboard-read", "clipboard-write", "payment-handler"]);`

**Comment by C2BB** [comment] 2021-01-11 19:07
Same problem here

**Comment by Niek** [comment] 2021-01-11 19:34
The problem is that this is conflicting with the `navigator.permissions` evasion. To fix this, disable the evasion. Sample:
```js
const pluginStealth = require('puppeteer-extra-plugin-stealth')()
pluginStealth.enabledEvasions.delete('navigator.permissions')
puppeteer.use(pluginStealth)
```

**Comment by berstend** [comment] 2021-01-13 12:21
Theoretically [the code](https://github.com/berstend/puppeteer-extra/blob/master/packages/puppeteer-extra-plugin-stealth/evasions/navigator.permissions/index.js#L27) should only affect e.g. `await navigator.permissions.query({name:'notifications'})`

We can also check if there's a better way to spoof this by using CDP methods, instead of JS patching.

**Comment by Niek** [comment] 2021-01-13 12:27
There's `Browser.setPermission()`, but I'm not sure if/how that works in headless.

**Comment by berstend** [comment] 2021-02-15 10:54
`navigator.permissions` has been rewritten (#429) in `puppeteer-extra-plugin-stealth@2.7.5`, kindly test if this is still an issue (closing for now).

**Closed by berstend** 2021-02-15 10:54 UTC
Labels: ongoing-research, plugin: stealth ㊙️, workaround-available
