### ISSUE TITLE
[Bug] Crash of process exit(1) [puppeteer-extra-plugin-recaptcha]

### ISSUE THREAD

**Issue by ergcode** [berstend/puppeteer-extra#392] opened 2020-12-12 22:32 UTC
When using the "puppeteer-extra-plugin-recaptcha" module, I often encounter the error:
```bash
exit(1)
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 89.108.117.181:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
Emitted 'error' event on ClientRequest instance at:
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '89.108.117.181',
  port: 80
}
```
It is most likely related to network problems.

We check the ip address and get the culprit:
```bash
host 89.108.117.181
181.117.108.89.in-addr.arpa domain name pointer 2captcha.com.
```

My packages in package.json:
```json
{
	"dependencies": {
		"cheerio": "^1.0.0-rc.3",
		"node-telegram-bot-api": "^0.50.0",
		"puppeteer": "^5.5.0",
		"puppeteer-extra": "^3.1.15",
		"puppeteer-extra-plugin-adblocker": "^2.11.9",
		"puppeteer-extra-plugin-recaptcha": "^3.3.0",
		"puppeteer-extra-plugin-stealth": "^2.6.5",
		"request": "^2.88.2",
		"simple-proxy-agent": "^1.1.0",
		"tough-cookie-file-store": "^2.0.2"
	}
}
```

Calling packages in index.js:
```javascript
const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth'); 
puppeteer.use(StealthPlugin());

const RecaptchaPlugin = require('puppeteer-extra-plugin-recaptcha'); 
puppeteer.use(
	RecaptchaPlugin({
		provider: {
			id: '2captcha',
			token: '<2captcha key>',
		},
		visualFeedback: true,
	})
);
```

Search by code in the project where the entry exit(1) was encountered.
![Screenshot_20201213_011630](https://user-images.githubusercontent.com/23062770/101996353-b876c900-3ce2-11eb-96cd-33ba5e0b8889.png)

All functions in the code are wrapped in try/catch. Process termination exit(1) - calls the package from dependencies.
Any ideas on how to fix the problem?

**Comment by berstend** [comment] 2021-01-13 15:39
This should be fixed since `3.2.2` with https://github.com/berstend/puppeteer-extra/pull/328

Closing this for now, please re-open in case this happens in the latest recaptcha plugin version.

**Comment by berstend** [comment] 2021-01-13 15:41
I just noticed you're using `3.3.0` as per your package.json 🤔

**Comment by berstend** [comment] 2021-01-13 15:44
Can you check if you can catch the error like this?

```js
process.on('uncaughtException', function (err) {
  console.log(err);
})
```

This would be meant as a temporary fix - a rewrite of the recaptcha plugin is in the pipeline.

**Comment by ergcode** [comment] 2021-01-13 16:04
I will try to upgrade to 3.2.2 and then track the error.

Now I solve the problem by restarting the process.

**Comment by berstend** [comment] 2021-01-19 06:41
@ergcode any update on this, is this still happening? :-)

**Comment by javflores** [comment] 2021-02-03 09:36
Hello @berstend I'm having the same problem.
Even after upgrading the issue is still happening for me.
This is my code but still not catching timeout from captcha api:
 ```
solveRecaptchasResult = await page.solveRecaptchas()
      .catch(err => {
        //Issues here https://github.com/berstend/puppeteer-extra/issues/392
        console.log("Captcha solving errors, very possibly a timeout");
        console.log(err);
      });
```
ie the catch is never reached.

**Comment by berstend** [comment] 2021-02-03 09:56
@javflores can you try wrapping that line with a `try/catch` instead of `.catch` and in addition check if [this](https://github.com/berstend/puppeteer-extra/issues/392#issuecomment-759533280) is catching the error?

**Comment by javflores** [comment] 2021-02-03 10:26
thanks @berstend !
I didn't show the whole code but I actually have another try/catch on top of that :D 
Here is the full code, you can see how this piece of code is giving me headeaches. 

```
try {
    solveRecaptchasResult = await page.solveRecaptchas()
      .catch(err => {
        //Issues here https://github.com/berstend/puppeteer-extra/issues/392
        console.log("Captcha solving errors, very possibly a timeout");
        console.log(err);
      });
    process.on('uncaughtException', function (err) {
      console.log(err);
      return;
    });
  } catch (e) {
    console.log(" Internal error when solving captcha");
    console.log(e);
    return;
  }
```
that try/catch wasn't catching things either and getting the error:
```
Trying  to solve captcha
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 89.108.117.181:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
Emitted 'error' event on ClientRequest instance at:
    at Socket.socketErrorListener (_http_client.js:427:9)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '89.108.117.181',
  port: 80
}
error Command failed with exit code 1.
```

I have now added as you can see also the process.on statement, and will try to see if this works.

**Comment by berstend** [comment] 2021-02-03 10:34
What's weird: In the stack trace there's only internal Node.js files listed, nothing related to the recaptcha plugin 🤔

**Comment by ergcode** [comment] 2021-02-03 11:40
> @ergcode any update on this, is this still happening? :-)
I apologize for the long wait.

Now my script periodically saves its state in JSON. And after the fall, it restores its state from this file. Therefore, the problem is not so critical.

But so far I have not been able to accurately track the error.

According to statistics:
- passed ~ 14000 captchas,
- 127 restarts after crashing in "pm2 monit".

package.json
```JSON
	"dependencies": {
		"puppeteer": "^5.5.0",
		"puppeteer-extra": "^3.1.16",
		"puppeteer-extra-plugin-recaptcha": "^3.3.2",
		"puppeteer-extra-plugin-stealth": "^2.6.7"
	},
```

I'll try to change the code from
code.js
```JS
		try {
			await page.waitForSelector(`#g-recaptcha`, { timeout: 10000 });
			await page.solveRecaptchas();
			await page.click(`#g-recaptcha`);
		} catch (error) { console.error(error); }
```

to this code
code.js
```JS
		try {
			process.on(`uncaughtException`, (error) => console.log(error));
			await page.waitForSelector(`#g-recaptcha`, { timeout: 10000 });
			await page.solveRecaptchas().catch((error) => console.error(error));
			await page.click(`#g-recaptcha`);
		} catch (error) { console.error(error); }
```

Maybe I'll get a little more data.

**Comment by berstend** [comment] 2021-02-03 11:43
@ergcode thanks for the feedback! Curious if `uncaughtException` is able to catch the error. Will do some digging as well, this feels like a Node.js related issue.

**Comment by berstend** [comment] 2021-02-07 05:58
@ergcode @javflores does `uncaughtException` catch it? :-)

**Comment by ergcode** [comment] 2021-02-07 09:40
> @ergcode @javflores does `uncaughtException` catch it? :-)

More than 5 days have passed since updating to "puppeteer-extra-plugin-recaptcha": "^ 3.3.2".
The number of restarts is still 127. That is, it has not changed.
9949 Captchas passed in 4 days.

I think the problem can be closed.
Thank you for your work.
And open the donation reception.

**Comment by berstend** [comment] 2021-02-07 09:48
@ergcode great to hear :-) Closing for now, I will keep this in mind when I do a planned rewrite of the recaptcha plugin.

PS: I added Github Sponsors links a few days ago :-)

**Closed by berstend** 2021-02-07 09:48 UTC
Labels: issue: bug report, more-info-needed, needs triage
