### ISSUE TITLE
TypeError: browser.setMaxListeners is not a function

### ISSUE THREAD

**Issue by kkmuffme** [berstend/puppeteer-extra#235] opened 2020-06-29 11:54 UTC
Followup to https://github.com/berstend/puppeteer-extra/issues/211

Since 4.0.0 this issue has reappeared and exists all the way up to the latest (4.4.0)

With 4.4.0 the suggested workaround of reinstalling puppeteer doesn't help either.

**Comment by brunogaspar** [comment] 2020-06-29 12:01
This issue is unfortunate but it's a duplicate of #228

**Comment by itsdarrylnorris** [comment] 2020-07-03 22:23
Hey @kkmuffme ,

Can we close this issue? Since is a duplicated of #228

**Comment by berstend** [comment] 2020-07-08 15:59
Duplicate of and fixed in #228.

**Closed by berstend** 2020-07-08 15:59 UTC
