### ISSUE TITLE
Stealth only works on newly created pages

### ISSUE THREAD

**Issue by njlr** [berstend/puppeteer-extra#88] opened 2019-12-05 13:11 UTC
I usually fetch the page like this:

```javascript
const [ page ] = await browser.pages();
```

But this page will not be appropriately "stealthed" (webdriver is set, IIRC). 

Instead you must do: 

```javascript
const page = await browser.newPage();
```

Ideally the initial page would also be "stealthed"; this was a subtle one that took me a while to find!

**Comment by berstend** [comment] 2019-12-05 15:04
Ah, I sometimes forget about that use-case 😄 If possible I'd recommend using new pages, as most pptr tooling works around the new-target-created events.

There's no technical reason for the stealth plugin not to work on existing pages, it's just that it currently only injects stuff when the `onPageCreated` event is fired. I recently just made a change to the recaptcha plugin to also enumerate potential open pages and inject it's payload there.

Given that we're now live for 2 years with half a million downloads and you're the first to notice I'm gonna assume most people create their pages as opposed to using existing ones 😄 

Anyhow, will implement a fix so existing pages get stealthed as well.

**Comment by berstend** [comment] 2019-12-05 15:14
I'm thinking about adding a new method to the base plugin: `onPage` (which behaves like `onPageCreated` + fired once for each existing page) to save some boilerplate in the plugins.

**Comment by shirshak55** [comment] 2019-12-05 15:17
yea I think recommended way is to use 
```
const page = await browser.newPage();
```
I don't see any reason to use 
```
const page = await browser.newPage();
```

**Comment by njlr** [comment] 2019-12-05 15:23
I think using the existing page saves a (very) small amount of RAM.

**Comment by shirshak55** [comment] 2019-12-05 15:29
hmm then close that and spawn new tab.  I think it is implication of chrome requiring at least one tab open so there is always a first tab?

**Comment by berstend** [comment] 2019-12-05 15:38
But yeah, will implement a fix soon :) @njlr sorry for the debug session to figure this out 😄

**Comment by berstend** [comment] 2019-12-05 15:55
PS, here's a workaround (untested) until I implemented the fix:

```js
const puppeteer = require("puppeteer-extra")

const StealthPlugin = require("puppeteer-extra-plugin-stealth")
const stealth = StealthPlugin()
puppeteer.use(stealth)


puppeteer.launch({ headless: false }).then(async browser => {
  // Add stealth to existing pages
  const pages = await browser.pages()
  for (const page in pages) {
    await stealth.onPageCreated(page)
  }

  await browser.close()
})
```

**Comment by KrisWu-188** [comment] 2020-02-22 05:51
@berstend If I use "puppeter extra plugin stearth" on the new page, it will be detected. If I don't use it, it won't be detected

**Comment by brunogaspar** [comment] 2020-02-22 14:44
@KrisWu-188 Any reproducible example you can share?

**Comment by SandratraRM** [comment] 2020-08-17 07:30
If the fix is not going to happen because of lack of people noticing the issue, then +1

**Comment by berstend** [comment] 2020-08-21 01:08
> took a very long time before figuring out what was wrong. 

This should be immediately noticeable when turning on debug mode as suggested in the docs.

**Comment by berstend** [comment] 2020-08-21 01:11
This is not affecting many people, otherwise there would be more activity or complaints in this issue. Given that there's a relatively clean workaround available and we have some much more pressing issues (playwright support, ongoing stealth stuff) this has a pretty low priority.

Happy to merge in a documented and tested PR though (I described in my first comment how I fixed this in the recaptcha plugin).

**Comment by berstend** [comment] 2020-10-22 14:24
Changing this to a `wontfix` - the demand for it is very low, a clean workaround available and I'm generally busy with more important things.

**Closed by berstend** 2020-10-22 14:24 UTC
Labels: wontfix, workaround-available

**Comment by oom-** [comment] 2021-02-04 12:01
Here is another workaround in case if later the modification made by the stealth plugin will need to be implemented before/during instantiation of the page: 

```js
const puppeteer = require("puppeteer-extra")

const StealthPlugin = require("puppeteer-extra-plugin-stealth")
const stealth = StealthPlugin()
puppeteer.use(stealth)

puppeteer.launch({ headless: false }).then(async browser => {
    let page = await browser.newPage(); //open new tab
    (await browser.pages())[0].close(); //close first one
  await browser.close()
})
```
