### ISSUE TITLE
Support for Invisible reCaptcha V2 in Puppeteer Extra Plugin Recaptcha 

### ISSUE THREAD

**Issue by jonkratz** [berstend/puppeteer-extra#300] opened 2020-08-26 15:54 UTC
Is anyone having success with solving Invisible reCaptchas with the puppeteer-extra-plugin-recaptcha? I see that 2captcha has described the process needed for them to solve the invisible recaptchas: https://2captcha.com/2captcha-api#invisible

If no one has has tried to solve this issue, I'd be happy to take a crack at it based on the documentation by 2captcha. I just wanted to find out if it had been tried and learn from any roadblocks encountered.

**Comment by berstend** [comment] 2020-08-27 19:39
Invisible recaptchas are supported by the plugin? Once they turn into a visible one the plugin will solve it - or what do you mean?

**Comment by bclougherty** [comment] 2020-08-28 18:59
I can confirm that it doesn't solve these correctly - `RecaptchaContentScript.getVisibleIframesIds()` is filtering out iframes where the `src` contains 'invisible'. Even when the captcha itself is visible on the page - it looks like it's triggered to display via js, but the plugin is still filtering it out based on the `src`.

**Comment by berstend** [comment] 2020-08-31 07:17
Thanks for the info, this will be one of things I'll be fixing. I'm gonna rewrite the recaptcha plugin from scratch once #303 + a new `stealth-pro` plugin supporting playwright has landed. :-)

**Comment by bclougherty** [comment] 2020-08-31 12:44
@berstend Would you accept a patch for the existing code? This is a pretty critical fix, for us.

**Closed** 2020-09-02 11:17 UTC

**Comment by berstend** [comment] 2020-09-02 11:22
@bclougherty your patch is published in `puppeteer-extra-plugin-recaptcha@3.1.18` - thanks 👍

**Comment by bclougherty** [comment] 2020-09-02 12:21
Thanks, @berstend!
