### ISSUE TITLE
iframe.contentWindow evasion causes troubles for some ad systems

### ISSUE THREAD

**Issue by methyl** [berstend/puppeteer-extra#137] opened 2020-01-10 13:19 UTC
Hello!

I've encountered a problem with `iframe.contentWindow` evasion. It seems to be breaking some of the websites that are displaying ads and I guess it's related to `srcdoc` attribute. With plugin enabled, the ad script instead of replacing iframe HTML content replaces whole page HTML.

You can see this being a case for eg. http://veganliftz.com/best-vegan-pre-workout.

Once I `pluginStealth.enabledEvasions.delete('iframe.contentWindow')` or enable adblocker, it starts to work again.

**Comment by Niek** [comment] 2020-01-10 14:49
Probably related to https://github.com/puppeteer/puppeteer/issues/1106

**Comment by berstend** [comment] 2020-09-02 11:52
As this is becoming the canonical ticket for this: The `iframe.contentWindow` evasion attempts to fix a nasty puppeteer bug but that comes at the expensive of some sites (specifically ad-infested ones) breaking.

Most often you don't need this evasion and can just disable it if you experience issues:

```js
pluginStealth.enabledEvasions.delete('iframe.contentWindow')
```

**Comment by Phyks** [comment] 2020-09-02 17:45
As per https://github.com/berstend/puppeteer-extra/issues/137#issuecomment-685680787, discarding this evasion or using an adblocker for websites full of ads might not be an option. Sometimes you **do** need the ads (e.g. for correct placements / layouts).

Would you have some opinion on the patch proposed above? https://github.com/berstend/puppeteer-extra/issues/202#issuecomment-645300106

Thanks!

**Comment by trnj** [comment] 2020-09-16 12:40
I've probably solved this issue and rewrote the plugin a bit. Need to test a bit. 

How does the check work? This way?
` /Chrome/.test(fingerprint.userAgent) && fingerprint.iframeChrome === 'undefined'
`
Right?

**Comment by Niek** [comment] 2020-09-16 13:43
> I've probably solved this issue and rewrote the plugin a bit. Need to test a bit.
> 
> How does the check work? This way?
> `/Chrome/.test(fingerprint.userAgent) && fingerprint.iframeChrome === 'undefined'`
> Right?

You can see the existing tests in https://github.com/berstend/puppeteer-extra/blob/master/packages/puppeteer-extra-plugin-stealth/evasions/iframe.contentWindow/index.test.js

Run the tests locally: ``npx ava -v``

**Comment by trnj** [comment] 2020-09-16 13:54
> Would you have some opinion on the patch proposed above? [#202 (comment)](https://github.com/berstend/puppeteer-extra/issues/202#issuecomment-645300106)

@Niek 
The proposed solution is wrong! The original code of @berstend was correct.

This probably does not need any solution anymore. So I suggest to revert back

```
+++              if (key === 'document') {
+++                return iframe.contentDocument;
+++              }
```

**Comment by trnj** [comment] 2020-09-16 14:11
Oops, very sorry, it was proposed by @Phyks  :) 

Agree, this one is correct

+++              if (key === 'document') {
+++                return iframe.contentDocument;
+++              }

**Comment by trnj** [comment] 2020-09-16 14:15
@Niek 

The above one by @Phyks is correct. I would suggest to change it a bit

+++ if (key === 'document') {
+++ return iframe.contentDocument || iframe.contentWindow.document;
+++ }

**Comment by Niek** [comment] 2020-09-16 18:35
PR @ https://github.com/berstend/puppeteer-extra/pull/327, closing this

**Closed by Niek** 2020-09-16 18:35 UTC
Labels: bug, plugin:stealth ㊙️, workaround-available

**Comment by raphaelpreston** [comment] 2020-11-23 03:53
I might be confused by the threads, but has this been reopened? I'm running `puppeteer-extra-plugin-stealth@2.6.5` and I'm still experiencing this issue (everything gets removed but the ads) on at least Best Buy. As before, deleting the `iframe.contentWindow` evasion fixes the problem.

**Comment by berstend** [comment] 2020-11-23 14:37
Pretty sure the issue isn't resolved altogether - the `iframe.contentWindow` is a pretty dirty hack unfortunately. The proper way would be to fix this in the driver instead (apparently playwright was able to do so) :-/
