### ISSUE TITLE
[TypeScript] Puppeteer-extra launching

### ISSUE THREAD

**Issue by KorrGoFF** [berstend/puppeteer-extra#46] opened 2019-06-25 12:58 UTC
```jsx
import * as puppeteer from "puppeteer-extra";
// init method
puppeteer.launch({ headless: true }).then(async browser => {
      const page = await browser.newPage()
      await page.setViewport({ width: 800, height: 600 })
      await page.goto("https://bot.sannysoft.com")
      await page.waitFor(5000)
    });
```
returns
Uncaught (in promise) TypeError: merge is not a function
    at PuppeteerExtra.launch (index.js:95)
    at _callee2$ (Controller.js:42)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:271)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at asyncGeneratorStep (Controller.js:7)
    at _next (Controller.js:9)
    at eval (Controller.js:9)
    at new Promise (<anonymous>)
    at Controller.eval (Controller.js:9)

What could be the problem?

dep:
    "@babel/polyfill": "^7.4.4",
    "@types/jquery": "^3.3.29",
    "@types/puppeteer": "^1.12.4",
    "@types/sizzle": "^2.3.2",
    "debug": "^4.1.1",
    "deepmerge": "^3.3.0",
    "kind-of": "^6.0.2",
    "ms": "^2.1.2",
    "puppeteer-cluster": "^0.16.0",
    "puppeteer-extra-plugin": "^3.0.4",
    "puppeteer-extra-plugin-anonymize-ua": "^2.1.4"

**Comment by leNicDev** [comment] 2019-09-25 18:36
Same issue here.

**Comment by gabsoft** [comment] 2019-10-02 22:42
I'm having error with puppeter extra on require or import
Try `npm install @types/puppeteer-extra` if it exists or add a new declaration (.d.ts) file containing `declare module 'puppeteer-extra';`ts(7016)

And puppeteer-extra do not have @types

**Comment by ColeTownsend** [comment] 2019-10-18 03:47
Ditto! Wondering if its ts-config related but no luck yet

**Comment by berstend** [comment] 2019-11-24 08:10
Hey there, I'm refactoring the core parts of puppeteer-extra in TS so this issues should be obsolete soon :)

**Comment by berstend** [comment] 2019-11-25 12:09
Closing as duplicate of #21

**Closed by berstend** 2019-11-25 12:09 UTC
Labels: work-in-progress

**Comment by lelinhtinh** [comment] 2019-11-26 15:51
If you get this error when using Webpack, here's how to fix it: https://github.com/webpack/webpack/issues/6584

https://github.com/berstend/puppeteer-extra/blob/2dd01ace8d0b2ae5be71ae0f7495ef8caa967e11/packages/puppeteer-extra/index.js#L20

**Comment by berstend** [comment] 2019-11-29 13:56
@KorrGoFF @leNicDev @ColeTownsend @gabsoft First class TypeScript support has just landed

```ts
import puppeteer from 'puppeteer-extra'

import RecaptchaPlugin from 'puppeteer-extra-plugin-recaptcha'
import StealthPlugin from 'puppeteer-extra-plugin-stealth'

puppeteer.use(RecaptchaPlugin()).use(StealthPlugin())

puppeteer.launch({ headless: false }).then(async browser => {
  const page = await browser.newPage()
  await page.setViewport({ width: 800, height: 600 })

  await page.goto('https://bot.sannysoft.com')
  await page.waitFor(5000)
  await page.screenshot({ path: 'stealth.png', fullPage: true })

  await browser.close()
})
```

![image](https://user-images.githubusercontent.com/1368633/69873140-cadcbb00-12b7-11ea-926c-5a5738832eac.png)

**Comment by kamalkech** [comment] 2023-12-03 00:25
this package not working on typescript apps, a lot of lot bugs

**Comment by nicubarbaros** [comment] 2024-01-16 15:03
<img width="857" alt="Screenshot 2024-01-16 at 17 03 12" src="https://github.com/berstend/puppeteer-extra/assets/6587086/2d73358a-c634-4eb6-8d21-8fb6a8036db0">

I get this from inside puppeteer-extra :(

**Comment by PeterYang03110** [comment] 2024-06-13 08:09
import puppeteer from 'puppeteer-extra';
import StealthPlugin from "puppeteer-extra-plugin-stealth";
import blockResourcesPlugin  from "puppeteer-extra-plugin-block-resources";
import { delay } from './common/delay';

puppeteer.use(StealthPlugin()).use(blockResourcesPlugin({blockedTypes: new Set(["image", "media", "font"])}))


this code is not working.
