### ISSUE TITLE
After loading certain sites, everything disappears except for the ads

### ISSUE THREAD

**Issue by cameronc56** [berstend/puppeteer-extra#274] opened 2020-08-03 20:38 UTC
Very weird issue we are noticing on certain sites. 

Run the following code, replacing the chrome executable path:

```
(async () => {                                                                                                          
    const puppeteer = require("puppeteer");                                                                             
    const browser = await puppeteer.launch({                                                                            
        "headless": false,                                                                                              
        "executablePath": "/usr/bin/google-chrome-stable",                                                              
        "dumpio": true,                                                                                                 
        "args": [                                                                                                       
            "--disk-cache-dir=./diskCache",                                                                             
            "--user-data-dir=./chromeDataDir",                                                                          
            "--start-maximized",                                                                                        
            "--no-sandbox",                                                                                             
            "--disable-setuid-sandbox",                                                                                 
            "--disable-infobars",                                                                                       
            "--start-maximized",                                                                                        
            "--enable-logging=stderr --v=0",                                                                            
            "--no-sandbox",                                                                                             
            "--disable-infobars",                                                                                       
            "--disable-dev-shm-usage",                                                                                  
            "--disable-features=site-per-process",                                                                      
            "--ssl-version-min=tls1.2",                                                                                 
            "--cipher-suite-blacklist=0X0001,0X0002,0X0003,0Xc013,0Xc014,0X009c,0x009d,0X000a"                          
        ],                                                                                                              
        "ignoreHTTPSErrors": false,                                                                                     
        "devtools": false,
        "defaultViewport" : null                                                                                                                                                                                      
    });                                                                                                                 
    const page = await browser.newPage();                                                                               
    await page.goto("https://www.walmart.ca");                                                                          
})();
```

You will notice that the page loads successfully. 

Now replace the require line in the code above to use puppeteer-extra: 

```
const puppeteer = require("puppeteer-extra");
// add stealth plugin and use defaults (all evasion techniques)
const stealth_plugin = require("puppeteer-extra-plugin-stealth");
puppeteer.use(stealth_plugin());
```

Notice: A second or two after the page loads, everything dissapears except for the ad. 

This repros (somewhat inconsistently, i assume depending on which ads get served) on the following sites: walmart.ca, jcpenney.com, bestbuy.com, theglobeandmail.com. I am sure we will find more

**Comment by cameronc56** [comment] 2020-08-03 22:26
Update: I have narrowed it down to an issue with the iframe.contentWindow evasion

**Comment by berstend** [comment] 2020-08-03 22:33
Yup, closing as a duplicate of https://github.com/berstend/puppeteer-extra/issues/137

**Closed by berstend** 2020-08-03 22:33 UTC
