### ISSUE TITLE
user-data-dir not found when making .exe with pkg

### ISSUE THREAD

**Issue by mcmgcls** [berstend/puppeteer-extra#586] opened 2021-10-28 12:20 UTC
Whenever I launch using puppeteer-extra I encountered the following error on exe.
Something to note is that I didn't use this the plugin below so maybe it's a dependency of puppeteer-extra, launching puppeteer I don't encounter this issue.
```
          A plugin listed 'puppeteer-extra-plugin-user-data-dir' as dependency,
          which is currently missing. Please install it:

          yarn add puppeteer-extra-plugin-user-data-dir

          Note: You don't need to require the plugin yourself,
          unless you want to modify it's default settings.
```

Tried the following but didn't work:
1. Require the puppeteer-extra-plugin-user-data-dir.
2. Added puppeteer-extra-plugin-user-data-dir as assets of pkg. (not encountered the error above but the application crashed)
3. Downgraded to version 3.1.18.
4. Added all "assets": "node_modules/**/*.*".

**Comment by TheJizel** [comment] 2021-11-08 04:51
I'm also having this problem.

@mcmgcls Where did you make this change you mentioned?

**Comment by TheJizel** [comment] 2021-11-08 05:08
The problem is fixed for me in the latest `pkg` version (`5.4.1`). Can anybody else confirm?

**Comment by mcmgcls** [comment] 2022-04-20 04:28
@TheJizel confirmed, I updated to 5.4.1 and the error didn't exists.

**Comment by berstend** [comment] 2022-07-04 10:00
Closing as per comments above

**Closed by berstend** 2022-07-04 10:00 UTC
Labels: issue: bug report, needs triage
