### ISSUE TITLE
Discord Captcha Not Working + Puppetter input error when account generated [Reoppened Issue]

### ISSUE THREAD

**Issue by HiddenToolz** [berstend/puppeteer-extra#286] opened 2020-08-11 17:42 UTC
VIDEO : https://app.blackhole.run/#zJM1NcOozb15MMARCreJxAQebDwazreij1oJ9oAokAL7 
Skip after the first account generated, cuz it took me like 2 minutes to complete the captcha..

On the video, i also removed the code to confirm accounts
Also as we can confirm on this screen https://i.imgur.com/Gpnhs2S.png
I added the code gived by berstend to try again, but still no frames detected.
Here is a screen code : https://i.imgur.com/xrTYGY9.png 

Almost Full code Of the script (exclusing some calls and vars) : https://pastebin.com/WxeCzqFW

PS: sorry if i didn't replied literaly instantly to responses, i don't always recieve github notifications

**Comment by berstend** [comment] 2020-08-15 19:27
Uhm, nowhere in the [code](https://pastebin.com/WxeCzqFW) you mentioned you're using the recaptcha plugin? 😄 

I'm very sorry but it seems you're just a novice programmer from what I can tell and the issue is not related to `puppeteer-extra`. Stackoverflow is probably the better place to ask for help. Alternatively you could ask nicely in our chat if someone has a minute of their time for you to help debug your code.

Closing this for now.

**Closed by berstend** 2020-08-15 19:27 UTC

**Comment by HiddenToolz** [comment] 2020-08-18 15:13
> Uhm, nowhere in the [code](https://pastebin.com/WxeCzqFW) you mentioned you're using the recaptcha plugin? 
> 
> I'm very sorry but it seems you're just a novice programmer from what I can tell and the issue is not related to `puppeteer-extra`. Stackoverflow is probably the better place to ask for help. Alternatively you could ask nicely in our chat if someone has a minute of their time for you to help debug your code.
> 
> Closing this for now.

instead of always closing every request u should have some logic
I won't put again the captcha code because i am not at this point because as said **On the video, i also removed the code to confirm accounts
**
To just let you see that i try to output all mainframes, **that don't get output**
Also yes i have an problem on my post because puppeteer is crashing when trying to output header content **as shown on the video**
For your personal information no, i am not a random programmer. Thanks you for wasting my time
