### ISSUE TITLE
recaptcha methods are missing on initial browser's page

### ISSUE THREAD

**Issue by dmitrygorbenko** [berstend/puppeteer-extra#353] opened 2020-10-21 04:14 UTC
Consider this example
```
	//const page = await browser.newPage();
	const pages = await browser.pages();
	const page = pages[0];

	await page.goto('https://dmitriy.in.ua/');

	const frames = page.mainFrame().childFrames();
	const frame = frames[0];
	console.log(await frame.findRecaptchas());

	await browser.close();
```
It doesn't work, the error is:
```
(node:2074386) UnhandledPromiseRejectionWarning: TypeError: frame.findRecaptchas is not a function
```
But if you switch to newPage() method (which is used in tutorial) instead of using the current page, everything would work.

**Comment by brunogaspar** [comment] 2020-10-21 07:58
Duplicate of https://github.com/berstend/puppeteer-extra/issues/88

**Comment by prescience-data** [comment] 2020-10-21 10:19
Out of interest, what's the use-case for not using `await browser.newPage()` ?

**Comment by berstend** [comment] 2020-10-22 14:10
You could try the same workaround used for stealth for the time being:

```js
const puppeteer = require("puppeteer-extra")

const RecaptchaPlugin = require("puppeteer-extra-plugin-recaptcha")
const recaptcha = RecaptchaPlugin()
puppeteer.use(recaptcha)

puppeteer.launch({ headless: false }).then(async browser => {
  // Add recaptcha to existing pages
  const pages = await browser.pages()
  for (const page in pages) {
    await recaptcha.onPageCreated(page)
  }

  await browser.close()
})
```

There's pros and cons to add plugins to already existing pages, in the years this project exists the demand for this has been minimal so I lean towards not changing the behavior.

**Closed** 2020-10-22 14:10 UTC
Labels: wontfix, workaround-available

**Comment by dmitrygorbenko** [comment] 2020-10-24 04:04
@berstend  thank you !
@prescience-data I just wanted to use the page (tab) which already was opened by default, like, why do I need to create a new page ?

**Comment by shamsuzzamansadi** [comment] 2020-12-09 13:34
@berstend I've used your solution but it's showing now page.url not found. 
`const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
const RecaptchaPlugin = require('puppeteer-extra-plugin-recaptcha');
const recaptcha = RecaptchaPlugin({
    provider: {
      id: '2captcha',
      token: 'xxxxx', // REPLACE THIS WITH YOUR OWN 2CAPTCHA API KEY ⚡
    },
    visualFeedback: true, // colorize reCAPTCHAs (violet = detected, green = solved)
  });

const chromeOptions = {
    executablePath: "/usr/bin/google-chrome",
    headless: false,
    slowMo: 10,
    defaultViewport: null
};

puppeteer.use(
    StealthPlugin(),
   recaptcha
);

(async function main(){

    
    const browser = await puppeteer.launch(chromeOptions);
    const page = await browser.newPage();
    await page.setDefaultNavigationTimeout(0);
    await page.goto('https://register.mailbox.org/en',{
      waitUntil: 'networkidle2',
    });
    
    
    //username
    await page.waitForSelector('input[id="mail"]');
    let username = 'dumbjohn' + Math.random();
    console.log(username);
    await page.type('input[id="mail"]',`${username}`);

    //password
    await page.waitForSelector('input[name="passwort"]');
    await page.type('input[name="passwort"]','as@sNn123!qPn');

    //confirmPassword
    await page.waitForSelector('input[name="passwort2"]');
    await page.type('input[name="passwort2"]','as@sNn123!qPn');


    //click submit button
    // await timeout(1000);
    await page.waitForSelector('input[id="register_form_submit"]');
    await page.click('input[id="register_form_submit"]');
    
    //firstname
    await page.waitForSelector('input[name=vorname]');
    await page.type('input[name=vorname]','dumb');
   
    //lastname
    await page.waitForSelector('input[name=nachname]');
    await page.type('input[name=nachname]','john');

    //capchaSolver
    const pages = await browser.pages();
    for (const page in pages) {
        console.log('this is the page: ',page);
        await recaptcha.onPageCreated(page);
    }


    // await page.waitForSelector(`#recaptcha-anchor`);
    // await page.click(`#recaptcha-anchor`);

    //checkbox
    await page.waitForSelector('input[id=datenschutz]');
    await page.click('input[id=datenschutz]');

    await page.waitForSelector('input[id=agb]');
    await page.click('input[id=agb]');
    
    await page.waitForSelector('input[id=widerruf]');
    await page.click('input[id=widerruf]');

    
    //submitButton
    
    await page.waitForSelector('input[id="register_form_submit"]');
    await page.click('input[id="register_form_submit"]');

    //nevigating to secure level 3 wait here and then do other things
    
    //checkbox
    await page.waitForSelector('input[id=skip_pwreset]');
    await page.click('input[id=skip_pwreset]');

    //the submitButton
    await page.waitForSelector('input[id=extradata_form_submit]');
    await page.click('input[id=extradata_form_submit]');

    await page.waitForNavigation();

    await browser.close();
}
)();

`
The error is now:
`(node:26280) UnhandledPromiseRejectionWarning: TypeError: page.url is not a function
    at PuppeteerExtraPluginRecaptcha.onPageCreated (/home/xxx/Desktop/project work/email-creator-test/node_modules/puppeteer-extra-plugin-recaptcha/dist/index.cjs.js:873:42)
    at main (/home/xxx/Desktop/project test/email-creator-test/app.js:67:25)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26280) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:26280) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.                     `

**Comment by berstend** [comment] 2020-12-09 13:53
@shamsuzzamansadi first of your formatting is horrible, please use code fences properly :-)

Secondly, not sure what you're trying to do: You're using `browser.newPage` so this whole ticket doesn't apply to you.

**Comment by shamsuzzamansadi** [comment] 2020-12-09 14:08
@berstend  I've fixed it. I wanted to create a bot which will create email account on this mailbox.org. the problem is that they have this captcha on the page : https://register.mailbox.org/en/secure2 (basically second page after the first submission). I was so confused with the solution that I just copied your part of the solution and used it. Since the `page.solveRecaptchas` didn't worked.

**Comment by berstend** [comment] 2020-12-09 14:16
@shamsuzzamansadi good to hear you fixed it. In case your fix might be helpful for others feel free to share it. :-)

**Comment by shamsuzzamansadi** [comment] 2020-12-09 14:19
@berstend  I meant I've fixed the formatting not the error. :laughing: So I'm still having issues with the puppeteer extra plugin solveRecaptcha.

**Comment by berstend** [comment] 2020-12-09 14:23
@shamsuzzamansadi you need to remove that `recaptcha.onPageCreated(page)` stuff from your code. Can you try out the minimal example from the readme and see if that works for you?

**Comment by shamsuzzamansadi** [comment] 2020-12-09 14:40
When I try on line 63 this:
```
//capchaSolver
    await page.solveRecaptchas();
```
The error shows me:
```
(node:31405) UnhandledPromiseRejectionWarning: TypeError: page.solveRecaptchas is not a function
```
This page.solveRecaptchas() is said in the readme to use. However, doesn't worked and I googled. And end up here:
https://github.com/berstend/puppeteer-extra/issues/184

And the solution lead by you here. :confused: That made me confused. :sweat_smile:

**Comment by berstend** [comment] 2021-01-20 08:32
@shamsuzzamansadi did you try the workaround mentioned in [my comment above](https://github.com/berstend/puppeteer-extra/issues/353#issuecomment-714521257)?

**Comment by berstend** [comment] 2021-01-20 08:34
@shamsuzzamansadi 

```js
 puppeteer.use(
     StealthPlugin(),
     recaptcha
 );
```

This is incorrect usage, please refer to the demo code in the readme. :-)

**Comment by iamgbayer** [comment] 2021-03-05 00:42
I had the same error of @shamsuzzamansadi, `page.solveRecaptchas is not a function`.

I already tried that approach that you commented @berstend, but I've received the other error `TypeError: page.url is not a function` too.

**Comment by berstend** [comment] 2021-03-05 01:00
> I had the same error of @shamsuzzamansadi, `page.solveRecaptchas is not a function`.
> 
> I already tried that approach that you commented @berstend, but I've received the other error `TypeError: page.url is not a function` too.

That error message indicates that your problem is something else or you're not using the fix correctly? (`page.url()` is a pptr native thing)

Can you post a minimal example that shows this issue?

**Comment by Nyceane** [comment] 2023-05-22 02:56
Anyone solved this?  This is directly on the page:

  let { captchas, filtered, error } = await page.findRecaptchas()

and I am getting [] empty captchas.
