### ISSUE TITLE
puppeteer-extra-plugin-stealth not working

### ISSUE THREAD

**Issue by dongdoan0040** [berstend/puppeteer-extra#225] opened 2020-06-13 05:51 UTC
**puppeteer-extra-plugin-stealth** not work with  Invisible **reCaptcha** v2 
Please update the library or suggest me another way 
Thanks !!!!

**Comment by brunogaspar** [comment] 2020-06-28 08:27
Duplicate of #204

**Comment by itsdarrylnorris** [comment] 2020-07-31 18:03
Closing this ticket since is duplicated.

**Closed by itsdarrylnorris** 2020-07-31 18:03 UTC
