### ISSUE TITLE
Supporting Google Meet

### ISSUE THREAD

**Issue by mp3michael** [berstend/puppeteer-extra#334] opened 2020-09-21 23:31 UTC
Am building a robot to login and record video meetings and puppeteer-extra is proving quite valuable!

Unfortunately Google Meet isn't fooled. Any connection using Google Meet is identified as a bot and blocked. 

Anyone have experience with this or have a workaround?

**Comment by evading-bot-detection** [comment] 2020-09-22 12:50
this is interesting. Are you logging into a Google account beforehand?

**Comment by mp3michael** [comment] 2020-09-22 13:18
No we're not. We building a service for the public and so we are using an unauthenticated web interface to connect to the meeting, record it and then send the user a video.

We're wanting to launch with Zoom, Meet and Teams but it seems Meet is very wise to Puppeteer. Even with your plugin it detects Puppeteer.

**Comment by trnj** [comment] 2020-09-22 16:20
How exactly does it detect ?  Could you provide a screenshot or any logs, or any comparison of data with and without puppeteer.  Does it detect on client side? If yes, there should be some requests with captured information about your browser.

**Comment by mp3michael** [comment] 2020-09-23 02:42
I'll get this info and add it to this thread. Standby...

**Comment by s-artemenko** [comment] 2020-09-23 12:07
Steps to reproduce:

1. Create a meeting on meet.google.com, get the meeting link (in my case https://meet.google.com/ypd-hohe-vhs)

2. Start incognito Chrome or Chromium and use the link to join the meeting:

![chrome](https://user-images.githubusercontent.com/71767222/94009848-54103180-fda5-11ea-9897-7e307b55832a.png)

3. Run puppeteer:
```

const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
puppeteer.use(StealthPlugin());
var browser = await puppeteer.launch({headless: false,
args : ['--incognito',
'--disable-features=IsolateOrigins,site-per-process',
'--disable-infobars',
'--no-sandbox',
'--disable-setuid-sandbox',
]
});
var page = (await browser.pages())[0];
await page.goto('https://meet.google.com/ypd-hohe-vhs', {
waitUntil: "networkidle0",
timeout: 120000
});

```

"You can't join this video call" is shown.
In the log you can see that POST request "ResolveMeetingSpace" is failed.

![puppeteer](https://user-images.githubusercontent.com/71767222/94009856-570b2200-fda5-11ea-9ca5-7edca0a9492f.png)

**Comment by trnj** [comment] 2020-09-23 12:16
> Steps to reproduce:

Шалом. Прикольно. Может какие-то возможности отключены ? 
А если попробовать в Playwright с Firefox?

**Comment by s-artemenko** [comment] 2020-09-23 12:21
Привет. Пиши по английски плиз, mp3michael не понимает, он следит.
I didn't try with Playwright.

**Comment by trnj** [comment] 2020-09-23 13:54
Well, it worked for me in Playwright + Firefox. 

When you launch google meet, there is a script fired immediately, browserinfo. It passes using this plugin. 

Then, I think Meet is unable to store some auth cookies, according to the error.

**Comment by trnj** [comment] 2020-09-23 13:58
I think Firefox is way to go as for now. Mozilla cares about privacy. Just remove webdriver manually and other fingerprint

**Comment by trnj** [comment] 2020-09-23 14:17
Try using the firefox version of this plugin

**Comment by s-artemenko** [comment] 2020-09-23 14:41
Thank you.
We are using some Chrome extension, therefore it will be difficult to switch to Firefox.
Do you see any way to make it works on  puppeteer + Chrome/Chromium?

**Comment by trnj** [comment] 2020-09-23 15:00
> Thank you.
> We are using some Chrome extension, therefore it will be difficult to switch to Firefox.
> Do you see any way to make it works on puppeteer + Chrome/Chromium?

I'd highly recommend this option enabled
`await page.setBypassCSP(true)`

When you load Meet, there are a bunch of errors in console. Trackdown the exact reason.
There is a bug in 2.6.1, so try to downdtrade to the previous versions, like 2.6.0

If I could login using Firefox with obvious fingerprint, and enable videos, then there is no protection in place, they do not track bots.

**Comment by s-artemenko** [comment] 2020-09-23 15:12
> > Thank you.
> > We are using some Chrome extension, therefore it will be difficult to switch to Firefox.
> > Do you see any way to make it works on puppeteer + Chrome/Chromium?
> 
> I'd highly recommend this option enabled
> `await page.setBypassCSP(true)`
> 
> When you load Meet, there are a bunch of errors in console. Trackdown the exact reason.
> There is a bug in 2.6.1, so try to downdtrade to the previous versions, like 2.6.0
> 
> If I could login using Firefox with obvious fingerprint, and enable videos, then there is no protection in place, they do not track bots.

Ok, thank you. I will try.

**Comment by berstend** [comment] 2020-09-27 16:37
Closing until there's more technical info provided.

**Closed by berstend** 2020-09-27 16:37 UTC

**Comment by namnm** [comment] 2022-02-20 13:05
Having the same issue, not sure how to get pass this

**Comment by navicstein** [comment] 2022-05-13 13:15
You can try to use this stealth plugin

https://www.npmjs.com/package/puppeteer-extra

**Comment by thearnica** [comment] 2023-01-15 08:56
Confirmed to work with Stealth plugin

**Comment by yehorpenshyn** [comment] 2024-02-26 12:23
Unfortunately, I'm having the same issue. I use puppeteer-extra library to launch the browser and page, but I already have had this label 'You can't join this video call', before joining. Therefore a few days ago everything works correctly.

Also I use stealth plugin

**Comment by siddharthbulia** [comment] 2024-03-01 13:56
Not working for me either. Using stealth plugin.

**Comment by Hassaan11** [comment] 2024-03-11 06:20
Its works if I logs into google account before joining the meeting but without google login its not working for me either.

**Comment by akumar044** [comment] 2024-04-11 13:41
Has anyone figured out a solution for this? @Hassaan11 @siddharthbulia @yehorpenshyn 

So far I have used the StealthPlugin and removed these evasions

`stealthPlugin.enabledEvasions.delete("iframe.contentWindow");
stealthPlugin.enabledEvasions.delete("media.codecs");`

Nothing seems to be working. Before joining the meeting I get "You can't join this video call".

**Comment by yehorpenshyn** [comment] 2024-04-11 13:46
@akumar044 which version of puppeteer do u use?

I had the same error earlier and I found the issue in puppeteer versioning after my upgrading puppeteer package. Just downgrade the version and everything is working perfectly.

**Comment by akumar044** [comment] 2024-04-11 14:10
I'm using these versions @yehorpenshyn 

`"puppeteer": "22.4.1",
  "puppeteer-extra": "^3.3.4",
  "puppeteer-extra-plugin-stealth": "^2.11.1"`

**Comment by yehorpenshyn** [comment] 2024-04-11 14:13
@akumar044 try to use my list of versions
```
"puppeteer": "^20.9.0", "puppeteer-extra": "^3.3.6", "puppeteer-extra-plugin-stealth": "^2.11.2",
```

**Comment by akumar044** [comment] 2024-04-11 19:36
Awesome, it worked!. I'm using `"puppeteer-stream": "3.0.9"` and the above 3 versions are compatible with it.

Thankyou @yehorpenshyn

**Comment by Hassaan11** [comment] 2024-04-17 13:40
const { executablePath } = require('puppeteer')

I am using "puppeteer": "^19.6.3", "puppeteer-extra": "^3.3.4", "puppeteer-extra-plugin-stealth": "^2.11.1",

this.browser = await launch(puppeteer, {
        // executablePath: '/usr/local/bin/chromium',
        executablePath: executablePath(),
        devtools: false,
        headless: false,
        defaultViewport: null,
        args: [
          '--no-sandbox',
          '--headless=new',
          '--disable-setuid-sandbox',
          '--ignore-certificate-errors',
          '--disable-dev-shm-usage',
          '--enable-features=ChromeBrowserCloudManagement',
          '--disabled-setupid-sandbox',
        ],
      });
      
      its working fine if i use 
      `executablePath: executablePath(),`
      puppeteer joins the meeting without asking to login
      
      but if i try to use custom chromium path like 
      // executablePath: '/usr/local/bin/chromium',
      then it wont work it gives 403 error.

**Comment by tamagoeggo** [comment] 2024-05-03 02:57
If you didn’t want to deal with the complexities of implementing this yourself, an alternative is to use [Recall.ai](http://www.recall.ai/) for your meeting bots instead. It’s a simple 3rd party API that lets you use meeting bots to get raw audio/video from meetings without you needing to spend months to build, scale and maintain these bots.

Disclaimer: I’m one of the founders.

**Comment by princemishra01** [comment] 2024-05-22 13:40
> rtunately Google Meet isn't fooled. Any conn

Hi @akumar044 We were trying the same thing, to get the recorded stream through puppeteer-extra and  puppeteer-extra-plugin-stealth, but we are still not able to bypass the google authentication and getting the message "you can't join this video call".
By the above discussion I came to know that you have resolved this issue using the different version of above mentioned packages, but we are still not able to resolve it. Here is our code approach we followed to tackle this 

```js
const { launch, getStream } = require("../dist/PuppeteerStream");
const fs = require("fs");
const { executablePath } = require("puppeteer");

// make sure to install puppeteer-extra & puppeteer-extra-plugin-stealth to use this example
const puppeteer = require("puppeteer-extra");
const StealthPlugin = require("puppeteer-extra-plugin-stealth");

puppeteer.use(StealthPlugin());

const file = fs.createWriteStream(__dirname + "/test.webm");

async function test() {
  const browser = await launch(puppeteer, {
    executablePath: executablePath(),
    defaultViewport: {
      width: 1920,
      height: 1080,
    },
  });

  const page = await browser.newPage();
  await page.goto("https://meet.google.com/yto-rnuz-ink");
  const stream = await getStream(page, { audio: true, video: true });
  console.log("recording");

  stream.pipe(file);
  setTimeout(async () => {
    stream.destroy();
    await page.close();
    await browser.close();
    file.close();
    console.log("finished");
  }, 1000 * 10);
}

test();
```

Can you please be able to guide us through this to resolve the issue?

Thanks in advance

**Comment by akumar044** [comment] 2024-05-24 13:57
Hi @princemishra01, I faced the same issue sometime back. I believe adding this should work

`
const stealthPlugin = StealthPlugin();
stealthPlugin.enabledEvasions.delete("iframe.contentWindow");
stealthPlugin.enabledEvasions.delete("media.codecs");
puppeteer.use(stealthPlugin);`

Let me know how it goes!

**Comment by Spenquatch** [comment] 2024-07-28 00:33
Using the suggestions here I have been able to get google meet to let me join locally on my PC, but when I try it in a Docker container it always gives me the "You can't join this video call" page. Any suggestions?

**Comment by buddhikajay** [comment] 2024-08-04 01:20
I've created a sample project [here](https://github.com/meetrix/google-meet-bot).
@Spenquatch inside docker, I can make it work when I run `xvfb-run --auto-servernum --server-args='-screen 0 1280x720x24' npm start` but does not work when I add that to CMD.
This might be related to [this](https://github.com/microsoft/playwright/issues/14250#issuecomment-1131409074). Please consider raising an MR if you find a solution

**Comment by Leandree** [comment] 2025-03-26 20:22
I encounter so many "You can't join this video call" error since january ? Some days 0 error and other days i can have up to 12 on more than 100 meetings.
Am i the only one to still struggle with this error ? 
I have tried to switch on playright and playwright stealth. Seams a bit better but I did not managed to completely remove this error ...
I have also tried to add a lot of human like interaction on the dom.
Do you have any chrome version that permit to avoid this errors ?

**Comment by aijcoa** [comment] 2025-03-28 17:47
Did you figure anything out on the Chrome Version @Leandree ?

**Comment by Leandree** [comment] 2025-03-30 21:35
Not yet ...
Currently I am ont the 116.x and it has reduced the error rate but it did not completely disappear ...

**Comment by vladtreny** [comment] 2025-03-30 21:37
Send full code to reproduce

**Comment by CyberPanCake3000** [comment] 2025-04-07 17:54
> i can have up to 12 on more than 100 meetings.

this is very similar to what i encountered, but i have been getting OOM quite often lately. has this happened to you?

**Comment by vince2000** [comment] 2025-04-09 10:26
I tried automating the process of joining Google Meet using Puppeteer, and everything works fine. However, after running for a while, the SyncMeetingSpaceCollections API returns 429, and then the page directly redirects to this page.
I used a k8s to run it, so each time a completely new Chrome instance is used, and it runs in headless mode
And I found that if I run it locally using a Chrome instance with usage history in headless mode, it seems that the 429 is not triggered
version:
+-- puppeteer-extra-plugin-stealth@2.11.2
+-- puppeteer-extra@3.3.6
`-- puppeteer@22.15.0

![Image](https://github.com/user-attachments/assets/a61ffec9-bbfe-4905-a25a-f60e4d2a34a6)

**Comment by Leandree** [comment] 2025-04-14 16:30
@CyberPanCake3000 I don't have memory problem in my case. When it happen, i just reload the tab but it can still block even after 5 retries.

@vince2000 Oh very interesting, I will try to add usage history ! Each bot also run in it's own pod in k8s in my case !

**Comment by vince2000** [comment] 2025-04-15 01:56
@Leandree  Have you encountered a similar issue? Could you share your automation code?

**Comment by bdegomme** [comment] 2025-04-15 15:53
FYI encountering the same issue ("the meeting is full") since last monday. Before that we also got "You can't join this video call" sometimes, but retrying worked.
The SyncMeetingSpaceCollections 429 error mentions a rate limit of 600 requests per second per user, and the gmeet client makes a request every 5s so if Gmeet detects more than 50 bots that it considers to be the same user, it will raise this error.
And we're not using signed in users, I suppose gmeet upgraded how they do browser fingerprinting to group multiple bots as a single "user".
This happens even if each bot has a distinct IP address. I've tried modifying the user-agent, adding timeouts between clicks and make mouse movements more human-like, to no avail.

**Comment by vince2000** [comment] 2025-04-16 02:43
@bdegomme It seems we're using a similar approach. Is your solution with different IPs based on a network proxy?

**Comment by bdegomme** [comment] 2025-04-16 06:26
No just a new AWS provided IP address for each run

**Comment by Leandree** [comment] 2025-04-29 12:18
What's really strange is that it also often happen when using in local on my pc with no bot running in my cluster.
I think I can have a rate limit when a lot of bots but i can't explain the local problem...

**Comment by GauravDhyani-FS** [comment] 2025-05-18 23:57
Any Fix ? Still facing the same issue.

**Comment by vince2000** [comment] 2025-05-19 02:15
It’s still unresolved, but in my tests with the Google Meet bots from vendors like Otter.ai and Fathom, they don’t seem to have these issues.

**Comment by bdegomme** [comment] 2025-05-19 07:41
I do not have the issue anymore.
It may have been this line
`page = await browser.newPage({ storageState: { cookies: [], origins: [] } });`
Or some change on gmeet's side, I'm not sure.

**Comment by vince2000** [comment] 2025-05-19 08:09
@bdegomme  Which version are you using? On my side, the newPage method can’t accept the storageState parameter.

**Comment by bdegomme** [comment] 2025-05-19 08:25
puppeteer 23.11.1.
The real code is
```
  const browserContext = browser.defaultBrowserContext();
  ...
  page = await browserContext.newPage({ storageState: { cookies: [], origins: [] } });
```
Maybe `page = await browser.newPage({ storageState: { cookies: [], origins: [] } });` isn't valid, I was trying to simplify it for the answer

**Comment by vince2000** [comment] 2025-05-20 01:42
Indeed, the issue no longer occurs in our local and development environments. However, it still persists in the production environment. Moreover, instead of redirecting to the "Meeting is full" page, it now triggers an `UpdateMeetingDevice` call, which returns a 401 response, and then the page redirects to the login screen.

**Comment by vince2000** [comment] 2025-07-02 01:41
Has anyone encountered a new Google Meet issue? When some Google Meet meeting require calling the /recaptcha/enterprise API, Puppeteer automation scripts will fail to make the request and throw net::ERR_ABORTED. This causes the CreateMeetingDevice call to also fail, ultimately preventing the script from joining the meeting.

![Image](https://github.com/user-attachments/assets/ad36a796-d997-4944-8733-74d605d1771a)

**Comment by monil311** [comment] 2025-08-07 08:06
**Subject:** Google Meet Bot - Navigation Redirected to about: blank with 403 Error (Puppeteer + Stealth)

Hello community 👋

I’m currently working on a bot that joins a Google Meet call programmatically using Puppeteer with the following stack:

📦 Package Versions:

"puppeteer": "^24.13.0",
"puppeteer-extra": "^3.3.6",
"puppeteer-extra-plugin-stealth": "^2.11.2",
"puppeteer-stream": "^3.0.20"



When deployed to a server (with Docker), we encounter the following behavior:

- Browser launches
- Frame navigates to the expected Meet URL 
- Immediately redirects to about: blank
- Console logs multiple errors such as:
- Console error: Failed to load resource: the server responded with a status of 403 ()


Have others encountered this 403 → about: blank redirection while using Puppeteer with Google services?


Any advice, workarounds, or best practices for preventing Google from detecting the bot in this context would be greatly appreciated 🙏

Thanks in advance!
