### ISSUE TITLE
puppeteer-extra-plugin-block-resources is incompatible with puppeteer-extra-plugin-adblocker (Error: Request is already handled!)

### ISSUE THREAD

**Issue by Alfagun74** [berstend/puppeteer-extra#373] opened 2020-11-12 00:52 UTC
`puppeteer-extra-plugin-block-resources` is incompatible with `puppeteer-extra-plugin-adblocker`.

I want to use those two plugins together to efficiently filter out unnecessary resources (images, fonts, css), annoying trackers and bad ad domains. But i get tons of ```UnhandledPromiseRejectionWarning: Error: Request is already handled!``` Errors when doing it. The reason is that the Packages "steal" the requests from each other and handle them, so the other one can't.

Why wont we just combine those two packages to one? For example using a blockAds & blockTracker option in the block-resources plugin. Or maybe make a third package, that supports both simultaneously. ¯\_(ツ)_/¯

To go even further i unfortunately can't even handle any page.on("request") manually anymore using either one of those. So i need this feature to use both of these plugins, or i cant use any of them and just handle everything manually.

**Comment by berstend** [comment] 2020-11-14 00:04
Duplicate of #364

**Closed by berstend** 2020-11-14 00:04 UTC
